core/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('' , views.home , name="home"),
    path('aboutme/' ,views.aboutme , name="about" ),
    path('impressum/' , views.impressum , name="impressum"),
    path('contact/' , views.contact , name="contact"),
    path('galerie/' , views.galerie , name="galerie"),
]

project/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls') ),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.
class Galerie(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="images")

    def __str__(self):
        return self.name



class Kontakt(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=130)
    telephone = models.CharField(max_length=100)
    Ihre_Nachricht = models.TextField(max_length=400)
    sent_data_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

core/forms.py
from django import forms 
from .models import Galerie , Kontakt



class ContactForm(forms.ModelForm):
    name = forms.CharField(label="Name")
    telephone = forms.CharField(label="Telefonnumer")
    email = forms.EmailField(label="E-Mail-address")
    class Meta:
        model = Kontakt
        fields = '__all__'


class AddPicture(forms.ModelForm):
    class Meta:
        model  = Galerie
        fields = ['name' , 'image']

core/views.py
from django.shortcuts import render , redirect
from .models import Galerie , Kontakt
from .forms import ContactForm
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def home(request):
    return render(request , 'core/index.html' , {})


def aboutme(request):
    return render(request , 'core/über-mich.html' , {})


def impressum(request):
    return render(request , 'core/impressum.html',{})


def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request , "Ihre Nachricht wurde gesendet")
            return redirect(reverse('main:contact_page'))
        else:
            messages.warning(request , "Ihre Nachricht wurde nicht gesendet")
            return redirect(reverse('main:contact'))
    else:
        form = ContactForm()
        
    return render(request , 'core/kontakt.html', {
        'form':form
    })

def galerie(request):
    galerie = Galerie.objects.all()
    return render(request , 'core/galerie.html',{
        'galerie':galerie
    })

core/templates/core/galerie.html
{% load static %}
<html>
    <head>
        <title>ñliz canan alheraki</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <meta charset="utf-8">
        <link rel="icon" href="{% static 'images/2.png' %}">
        {% include "css.html" %}
    </head>
    <body>
        <div class="container">
        
        <button id="scrollUp">
        <i class="fas fa-arrow-up"></i>
        </button>
        
        
        <div class="head-nav">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <a class="navbar-brand" href="/"><img src="{% static 'images/1.jpeg' %}" width="325px"height="100px"></a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item li">
                       <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                          </li>
                        </ul>
                </div>
            </nav>        
        </div>
        <hr>
             <div class="head-nav ">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollabse" aria-controls="navCollabse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navCollabse">
                        <ul class="navbar-nav ml-auto">
                          <li class="nav-item ">
                            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item active">
                            <a class="nav-link" href="{% url 'main:galerie' %}">Galerie</a>
							</li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:about' %}">über mich</a>
                          </li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:contact' %}">Kontakt</a>
                          </li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:impressum' %}">Impressum</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>        
        </div>
<hr>
            <div class="courses" id="course">
                <div class="container">
                    <h2 class="text-center">Blindergalerie</h2>
                    <p class="lead text-center">Hallo </p>
                    <div class="main-course">
                        <div class="row">
                            {% for i in galerie %}
                                <div class="col-md-4">
                                    <a href=""> <img src="{{ i.image.url }}"></a>
                                   
                                </div>
                                {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        
        <hr>
                <!--Start Sign In-->
            <div class="signin" id="sign">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>ABONNIEREN SIE UNSEREN NEWSLETTER NEWSLETTER</h4>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <a href="#"><button>NEWSLETTER</button></a>
                        </div>
                    </div>
                </div>
            </div>
        <!--End Sign In-->
        <hr>
       
        <!--Start Footer-->
            <div class="footer" >
                <div class="container">
                    <div class="row">
                         <div class ="col-md-4">
                            <h2>KONTAKT</h2>
                             <p class="lead">Anfahrt Öffnungszeiten Mo- 900-00 Hier finden Sie uns: Alexanderstrale 5, 10178 Berlin, Deutschland Sa- So Geschlossen E-Mail mailgexample.com Rufen Sie uns an 0229 55 99 s55</p>
                        <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                        <div class ="col-md-4">
                            <h1>ANFAHRT</h1>
                          <div class="mapouter"><div class="gmap_canvas"><iframe width="333" height="197" id="gmap_canvas" src="https://www.google.com/maps/embed?" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to.org"></a><br><style>.mapouter{position:relative;text-align:right;height:197px;width:333px;}</style><a href="https://www.embedgooglemap.net">embedding maps</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:197px;width:333px;}</style></div></div>
                        </div>
                      
                     <div class ="col-md-4">
                            <h2>Öffnungszeiten</h2>
                            <ul>
                                <li><a href="/"><i class="fas fa-chevron-right"></i> MO - FR</a></li>
                                <li><a href="#about"><i class="fas fa-chevron-right"></i> SA-SO</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <!--End  Footer-->
           </div>
        {% include "js.html" %}
           
    </body>
</html>

core/templates/core/impressum.html
{% load static %}
<html>
    <head>
        <title>ñliz canan alheraki</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <meta charset="utf-8">
        <link rel="icon" href="{% static 'images/2.png' %}">
        {% include "css.html" %}
    </head>
    <body>
        <div class="container">
        
        <button id="scrollUp">
        <i class="fas fa-arrow-up"></i>
        </button>
        
        
        <div class="head-nav">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                       <a class="navbar-brand" href="/"><img src="{% static 'images/1.jpeg' %}" width="325px"height="100px"></a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item li">
                                <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                          </li>
                        </ul>
                </div>
            </nav>        
        </div>
        <hr>
             <div class="head-nav ">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollabse" aria-controls="navCollabse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navCollabse">
                        <ul class="navbar-nav ml-auto">
                          <li class="nav-item ">
                            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:galerie' %}">Galerie</a>
							</li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:about' %}">über mich</a>
                          </li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:contact' %}">Kontakt</a>
                          </li><li class="nav-item active">
                            <a class="nav-link" href="{% url 'main:impressum' %}">Impressum</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>        
        </div>
<hr>
            <h1>Impressum</h1>
            <hr>
        <div class="about" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <h3>Verantwortlich:</h3>
                  <p class="lead">Bitte tragen Sie hier den Verantwortlichen für die Webseiten-Inhalte ein
                        </p>
                            <h3>Kontakt:</h3>
                  <p class="lead">B Bitte tragen Sie hier Ihre Kontaktdaten ein
                        </p>
                            <h3>Registereintrag:</h3>
                  <p class="lead">Bitte eintragen
                        </p>
                            <h3>Umsatzsteuer-ID:</h3>
                  <p class="lead"> Bitte tragen Sie hier Ihre Umsatzsteuer-ID ein 
                        </p>
                            <h3>Wirtschafts-Identifikatlonsnummer:</h3>
                  <p class="lead">Bitte tragen Sie hier ihre Wirtschafts-Identifikationsnummer ein
                        </p>
                            <h3>Aufsichtsbehörde:</h3>
                  <p class="lead">Bitte tragen Sie hier Ihre zuständige Aufsichtsbehörde ein
                        </p>
                    </div>
                </div>
            </div>
        </div>
            <hr>
        <!--Start Sign In-->
            <div class="signin" id="sign">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>ABONNIEREN SIE UNSEREN NEWSLETTER NEWSLETTER</h4>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <a href="#"><button>NEWSLETTER</button></a>
                        </div>
                    </div>
                </div>
            </div>
        <!--End Sign In-->
        <hr>
       
        <!--Start Footer-->
            <div class="footer" >
                <div class="container">
                    <div class="row">
                         <div class ="col-md-4">
                            <h2>KONTAKT</h2>
                             <p class="lead"> Hannover  , 015752173.....</p>
                        <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                        <div class ="col-md-4">
                            <h1>ANFAHRT</h1>
                          <div class="mapouter"><div class="gmap_canvas"><iframe width="333" height="197" id="gmap_canvas" src="https://www.google.com/maps/embed?" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to.org"></a><br><style>.mapouter{position:relative;text-align:right;height:197px;width:333px;}</style><a href="https://www.embedgooglemap.net">embedding maps</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:197px;width:333px;}</style></div></div>
                        </div>
                      
                     <div class ="col-md-4">
                            <h2>Öffnungszeiten</h2>
                            <ul>
                                <li><a href="/"><i class="fas fa-chevron-right"></i> MO - FR</a></li>
                                <li><a href="#about"><i class="fas fa-chevron-right"></i> SA-SO</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <!--End  Footer-->
    
         </div>
        <!--Start Adding Script Files-->
       {% include "js.html" %}
           
    </body>
</html>

core/templates/core/index.html
{% load static %}
<html>
    <head>
        <title>ñliz canan alheraki</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <meta charset="utf-8" >
        <link rel="icon" href="{% static 'images/2.png' %}">
        {% include "css.html" %}
    </head>
    <body>
        <div class="container">
        
        <button id="scrollUp">
        <i class="fas fa-arrow-up"></i>
        </button>
                
        <div class="head-nav">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <a class="navbar-brand" href="/"><img src="{% static 'images/1.jpeg' %}" width="325px"height="100px"></a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item li">
                                 <a href="#"><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                          </li>
                        </ul>
                </div>
            </nav>        
        </div>
        <hr>
             <div class="head-nav ">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollabse" aria-controls="navCollabse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navCollabse">
                        <ul class="navbar-nav ml-auto">
                          <li class="nav-item active ">
                            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:galerie' %}">Galerie</a>
							</li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:about' %}">über mich</a>
                          </li><li class="nav-item ">
                            <a class="nav-link" href="{% url 'main:contact' %}">Kontakt</a>
                          </li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:impressum' %}">Impressum</a>
							
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>        
        </div>
<hr>
        <h1> Herzlich Willkommen auf <br>meiner Website </h1>
            <hr>
        <div class="about" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                   <img src="{% static 'images/2.png' %}" width="100%">
                    </div>
                    <div class="col-md-6">
                         <h2>Achtsamer Umgang mit Vielfalt: „Interkulturelle“ & diversitätsbewusste Bildung</h2>
                        <p class="lead">
                           
                       KURZVORTRÄGE – WORKSHOPS – SEMINARE 
Achtsamer Umgang mit Vielfalt setzt für mich voraus, dass wir unsere eigene Lebenswelt und eigenen Prägungen hinterfragen. Je besser wir uns selbst verstehen, desto offener und sensibler können wir anderen individuellen Lebenswelten begegnen. Debatten und Gespräche über Themen wie Diskriminierung & Rassismus, Flucht & Migration oder auch Zugehörigkeit & (kulturelle) Identität werden mit einem hohen Maß an Emotionalität geführt. Daher bin ich davon überzeugt, dass Achtsamkeit eine wichtige Rolle bei der Entwicklung von Diversitätsbewusstsein spielt.
Alle Angebote eignen sich für Jugendgruppen genauso wie für Erwachse. Ich passe Inhalte und Themenschwerpunkte gerne an die jeweilige Zielgruppe an. 
                        </p>
                        <a href="{% url 'main:contact' %}">Jetzt Anfragen</a>               
                    </div>
                </div>
            
            </div>
        
        </div>
            <hr>
              <div class="about" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                   <img src="{% static 'images/3.png' %}" width="100%">
                    </div>
                    <div class="col-md-6">
                         <h2> tanzeinfach: Tanz & Empowerment</h2>
                        <p class="lead">
                 WORKSHOPS – JUNGGESELLINNENABSCHIEDE – HENNA NÄCHTE 
tanzeinfach sind Tanzpartys und Workshops für Frauen* im Safe-Space (= geschützter Ort, ohne Kameras und ohne Zuschauer). Ganz unter euch lernt ihr Ansätze aus dem Freestyle, dem Social Dance und von Body Empowerment kennen. Spätestens am Ende des Workshops sollte der Satz „Ich kann nicht tanzen“ der Vergangenheit angehören. Hier könnt ihr euch so richtig auslassen & zelebrieren!
Vorkenntnisse sind nicht nötig!
Ich stimme die Inhalte ganz individuell für euch ab. Ich freue mich auf eure Anfrage!
                        </p>
                    <a href="{% url 'main:contact' %}">Jetzt Anfragen</a>              
                    </div>
                </div>
            
            </div>
        
        </div>
            <hr>
        <!--Start Sign In-->
            <div class="signin" id="sign">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>ABONNIEREN SIE UNSEREN NEWSLETTER NEWSLETTER</h4>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <a href="#"><button>NEWSLETTER</button></a>
                        </div>
                    </div>
                </div>
            </div>
        <!--End Sign In-->
        <hr>
       
        <!--Start Footer-->
            <div class="footer" >
                <div class="container">
                    <div class="row">
                         <div class ="col-md-4">
                            <h2>KONTAKT</h2>
                             <p class="lead">Hannoverche str , 30627 Hannover . 015752173005</p>
                           <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                        <div class ="col-md-4">
                            <h1>ANFAHRT</h1>
                          <div class="mapouter"><div class="gmap_canvas"><iframe width="333" height="197" id="gmap_canvas" src="https://www.google.com/maps/embed?" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to.org"></a><br><style>.mapouter{position:relative;text-align:right;height:197px;width:333px;}</style><a href="https://www.embedgooglemap.net">embedding maps</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:197px;width:333px;}</style></div></div>
                        </div>
                      
                     <div class ="col-md-4">
                            <h2>Öffnungszeiten</h2>
                            <ul>
                                <li><a href="/"><i class="fas fa-chevron-right"></i> MO - FR</a></li>
                                <li><a href="#about"><i class="fas fa-chevron-right"></i> SA-SO</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <!--End  Footer-->
         </div>
        <!--Start Adding Script Files-->
       {% include "js.html" %}
    </body>
</html>

core/templates/core/kontakt.html
{% load static %}
{% load bootstrap4 %}
<html>
    <head>
        <title>ñliz canan alheraki</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">        
        <meta charset="utf-8">
           <link rel="icon" href="{% static 'images/2.png' %}">
        {% include "css.html" %}
    </head>
    <body>
        <div class="container">
        
        <button id="scrollUp">
        <i class="fas fa-arrow-up"></i>
        </button>
        
        
        <div class="head-nav">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <a class="navbar-brand" href="/"><img src="{% static 'images/1.jpeg' %}" width="325px"height="100px"></a>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item li">
                             <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                          </li>
                        </ul>
                </div>
            </nav>        
        </div>
        <hr>
             <div class="head-nav ">
                <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
                    <div class="container">
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navCollabse" aria-controls="navCollabse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navCollabse">
                        <ul class="navbar-nav ml-auto">
                          <li class="nav-item ">
                            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'main:galerie' %}">Galerie</a>
							</li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:about' %}">über mich</a>
                          </li><li class="nav-item active">
                            <a class="nav-link" href="{% url 'main:contact' %}">Kontakt</a>
                          </li><li class="nav-item">
                            <a class="nav-link" href="{% url 'main:impressum' %}">Impressum</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>        
        </div>
<hr>
        <div class="about" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                  <p class="lead">
            Haben Sie Fragen zu unserem Angebot? Wir sind gerne für Sie da. Füllen Sie einfach das Kontaktformular aus, und wir setzen uns zeitnah mit ihnen in Verbindung. Natürlich können Sie uns auch telefonisch erreichen, oder Sie besuchen uns direkt vor Ort wir freuen uns auf Sie!
                        </p>
                    </div>
                    <div class="col-md-6">
                         <h2>Ihre Nachricht an uns </h2>
                        <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit" value="senden">    
                        </form>
                    </div>
                </div>
            
            </div>
        
        </div>
            <hr>
        <!--Start Sign In-->
            <div class="signin" id="sign">
                <div class="container">
                    <div class="row">
                        <div class="col-md-8">
                            <h4>ABONNIEREN SIE UNSEREN NEWSLETTER NEWSLETTER</h4>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <a href="#"><button>NEWSLETTER</button></a>
                        </div>
                    </div>
                </div>
            </div>
        <!--End Sign In-->
        <hr>
       
        <!--Start Footer-->
            <div class="footer" >
                <div class="container">
                    <div class="row">
                         <div class ="col-md-4">
                            <h2>KONTAKT</h2>
                             <p class="lead">Anfahrt Öffnungszeiten Mo- 900-00 Hier finden Sie uns: Alexanderstrale 5, 10178 Berlin, Deutschland Sa- So Geschlossen E-Mail mailgexample.com Rufen Sie uns an 0229 55 99 s55</p>
                          <a><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                        <div class ="col-md-4">
                            <h1>ANFAHRT</h1>
                          <div class="mapouter"><div class="gmap_canvas"><iframe width="333" height="197" id="gmap_canvas" src="https://www.google.com/maps/embed?" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to.org"></a><br><style>.mapouter{position:relative;text-align:right;height:197px;width:333px;}</style><a href="https://www.embedgooglemap.net">embedding maps</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:197px;width:333px;}</style></div></div>
                        </div>
                      
                     <div class ="col-md-4">
                            <h2>Öffnungszeiten</h2>
                            <ul>
                                <li><a href="/"><i class="fas fa-chevron-right"></i> MO - FR</a></li>
                                <li><a href="#about"><i class="fas fa-chevron-right"></i> SA-SO</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        <!--End  Footer-->
         </div>
        <!--Start Adding Script Files-->
        {% include "js.html" %}
           
    </body>
</html>

templates/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
        <link href="https://fonts.googleapis.com/css2?family=Jost&family=Rubik&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/all.min.css' %}">